ERROR:root:Exception occured
Traceback (most recent call last):
  File "D:/ViteosModel2.0/125_Weiss_Production_loop_1_argument.py", line 933, in <module>
    stout_list = s2_out.split("|")
TypeError: a bytes-like object is required, not 'str'
